import React from 'react';
import {createRoot} from 'react-dom/client';
import '@fontsource/manrope/latin-400.css';
import '@fontsource/manrope/latin-600.css';
import '@fontsource/dm-sans/latin-400.css';
import {projects,contacts} from './profile.js';
import './resume.css';
const groups=[['Technical skills','Computer networking, web development, vulnerability assessment, application security testing, system administration, database management, Linux/Unix administration, version control, REST API development, Android development, CLI development, cryptography and encryption protocols.'],['Programming & tools','Python, Java, C, Bash/Shell, HTML/CSS, JavaScript, SQL, Android Studio, VS Code, Wireshark, Nmap, Burp Suite, Git & GitHub.'],['Soft skills','Critical thinking, time management, ethical decision-making, design thinking, perseverance and resilience.']];
function Resume(){return <><nav className="resume-toolbar" aria-label="Resume controls"><a href="/portfolio/#resume">← Back to portfolio</a><button onClick={()=>window.print()}>Print / Save as PDF</button></nav><main className="resume-sheet"><header><p className="resume-label">RESUME</p><h1>Sumit Pandey</h1><p className="resume-role">Computer Science & Engineering · Cybersecurity</p><div className="resume-contact"><a href={'mailto:'+contacts.email}>{contacts.email}</a><a href={contacts.github}>GitHub / Sumitt86</a><a href={contacts.linkedin}>LinkedIn ↗</a></div></header><section><h2>Education</h2><div className="entry-heading"><h3>MPSTME, NMIMS University</h3><span>2023–2027</span></div><p>B.Tech Computer Science and Engineering (Cybersecurity)</p></section><section><h2>Projects</h2>{projects.map(project=><article key={project.name}><div className="entry-heading"><h3>{project.name}</h3><span>{project.year}</span></div><p>{project.description}</p></article>)}</section><section><h2>Certification</h2><h3>Ethical Hacker Certification</h3><p>Cisco Networking Academy (NetAcad)</p></section><section><h2>Core skills</h2>{groups.map(([name,text])=><article className="skill-entry" key={name}><h3>{name}</h3><p>{text}</p></article>)}</section><section><h2>Leadership & responsibility</h2><article><div className="entry-heading"><h3>Sub-Head, Technical Department</h3><span>2024</span></div><p>International Society of Automation (ISA) Committee, MPSTME</p></article><article><div className="entry-heading"><h3>IAG Coordinator, Super Core</h3><span>2025</span></div><p>International Society of Automation (ISA) Committee, MPSTME</p></article><ul><li>Coordinated technical workshops and sessions, managed teams, and supported smooth event delivery.</li><li>Contributed to campus initiatives promoting automation and engineering awareness.</li></ul></section></main></>}
createRoot(document.getElementById('root')).render(<Resume/>);
